name: Deploy Portfolio Website
on:
  push:
    paths:
      - "portfolio/**"
      - ".github/workflows/deploy_portfolio.yml"

jobs:
  deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: install dependencies
        run: |
          cd portfolio
          npm ci
      - name: build app
        run: |
          cd portfolio
          npm run build
      - name: Copy dist to pi
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOME_SERVER_HOSTNAME }}
          username: ${{ secrets.HOME_SERVER_USERNAME }}
          strip_components: 3
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          source: "./portfolio/dist"
          target: "/home/${{ secrets.HOME_SERVER_USERNAME }}/dist/"
          rm: true
      - name: Copy setup script to pi
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOME_SERVER_HOSTNAME }}
          username: ${{ secrets.HOME_SERVER_USERNAME }}
          strip_components: 2
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          source: "./portfolio/setup.sh"
          target: "/home/${{ secrets.HOME_SERVER_USERNAME }}/portfolio/"
          rm: true
      - name: Trigger setup
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOME_SERVER_HOSTNAME }}
          username: ${{ secrets.HOME_SERVER_USERNAME }}
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          script: |
            sudo sh ~/portfolio/setup.sh
