name: Deploy Dynamic DNS Cron Job
on:
  push:
    paths:
      - "dynamic_dns/cron_job_rs/**"
      - ".github/workflows/deploy_cron_job_rs.yml"

jobs:
  deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set env variables
        run: |
          echo "LAMBDA_API_KEY=${{ secrets.LAMBDA_API_KEY }}" > dynamic_dns/cron_job_rs/.env
          echo "LAMBDA_ENDPOINT=${{ secrets.LAMBDA_ENDPOINT }}" >> dynamic_dns/cron_job_rs/.env
      - name: Copy scripts to pi
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOME_SERVER_HOSTNAME }}
          username: ${{ secrets.HOME_SERVER_USERNAME }}
          strip_components: 3
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          source: "./dynamic_dns/cron_job_rs"
          target: "/home/${{ secrets.HOME_SERVER_USERNAME }}/cron_job_rs/"
          rm: true
      - name: Trigger setup
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOME_SERVER_HOSTNAME }}
          username: ${{ secrets.HOME_SERVER_USERNAME }}
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          script: |
            sh ~/cron_job_rs/setup.sh
