name: Deploy Dynamic DNS Lambda Function
on:
  push:
    paths:
      - "dynamic_dns/lambda.py"
      - ".github/workflows/deploy_lambda.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Create target directory
        run: mkdir package

      - name: Install dependencies
        run: |
          pip install --target ./package -r dynamic_dns/lambda_requirements.txt

      - name: Create deployment package
        run: |
          cd package
          zip -r ../my-deployment-package.zip .
          cd ../dynamic_dns
          zip -g -r ../my-deployment-package.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name dynamicDNS --zip-file fileb://my-deployment-package.zip
