name: Deploy Dynamic DNS Cron Job
on:
  push:
    paths:
      - "dynamic_dns/cron_job/**"
      - ".github/workflows/deploy_cron_job.yml"

jobs:
  deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set env variables
        run: |
          echo "LAMBDA_API_KEY=${{ secrets.LAMBDA_API_KEY }}" > .env
          echo "LAMBDA_ENDPOINT=${{ secrets.LAMBDA_ENDPOINT }}" >> .env
      - name: Copy scripts to pi
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOME_SERVER_HOSTNAME }}
          username: ${{ secrets.HOME_SERVER_USERNAME }}
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          source: "./dynamic_dns/cron_job"
          target: "/home/${{ secrets.HOME_SERVER_USERNAME }}/"
          rm: true
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.REMOTE_SSH_KEY }}" > ~/.ssh/id_ecdsa
          chmod 600 ~/.ssh/id_ecdsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
      - name: Trigger setup
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "sh ~/cron_job/setup.sh"
