[package]
name = "cron_job_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.12.20", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }

